/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_experto_rorschach;

/**
 *
 * @author boyst
 */
public class DATOS extends javax.swing.JFrame {

    /**
     * Creates new form DATOS
     */
    public DATOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TOTAL1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JButton();
        d5 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        ENVIAR = new javax.swing.JButton();
        PUNTOSF = new javax.swing.JTextField();
        PUNTOS10 = new javax.swing.JTextField();
        PUNTOS1 = new javax.swing.JTextField();
        PUNTOS2 = new javax.swing.JTextField();
        PUNTOS3 = new javax.swing.JTextField();
        PUNTOS4 = new javax.swing.JTextField();
        PUNTOS5 = new javax.swing.JTextField();
        PUNTOS6 = new javax.swing.JTextField();
        PUNTOS7 = new javax.swing.JTextField();
        PUNTOS8 = new javax.swing.JTextField();
        PUNTOS9 = new javax.swing.JTextField();

        TOTAL1.setBackground(new java.awt.Color(153, 153, 255));
        TOTAL1.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        TOTAL1.setForeground(new java.awt.Color(0, 0, 51));
        TOTAL1.setText("TOTAL");
        TOTAL1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        TOTAL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TOTAL1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_experto_rorschach/1.jpg"))); // NOI18N
        LOGO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        jLabel2.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("TEST DE PERSONALIDAD ");

        jLabel3.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("RESUSLTADOS DE CADA UNA DE LAS IMAGINES ");

        jLabel4.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));

        jLabel5.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("RORSCHACH");

        d1.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d1.setForeground(new java.awt.Color(0, 0, 51));
        d1.setText("IMAGEN1");

        d3.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d3.setForeground(new java.awt.Color(0, 0, 51));
        d3.setText("IMAGEN3 ");

        d4.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d4.setForeground(new java.awt.Color(0, 0, 51));
        d4.setText("IMAGEN4");

        d2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d2.setForeground(new java.awt.Color(0, 0, 51));
        d2.setText("IMAGEN2");

        d6.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d6.setForeground(new java.awt.Color(0, 0, 51));
        d6.setText("IMAGEN6");

        TOTAL.setBackground(new java.awt.Color(153, 153, 255));
        TOTAL.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        TOTAL.setForeground(new java.awt.Color(0, 0, 51));
        TOTAL.setText("TOTAL");
        TOTAL.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        TOTAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TOTALMouseClicked(evt);
            }
        });
        TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALActionPerformed(evt);
            }
        });

        d5.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d5.setForeground(new java.awt.Color(0, 0, 51));
        d5.setText("IMAGEN5");

        d7.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d7.setForeground(new java.awt.Color(0, 0, 51));
        d7.setText("IMAGEN7");

        d8.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d8.setForeground(new java.awt.Color(0, 0, 51));
        d8.setText("IMAGEN8");

        d9.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d9.setForeground(new java.awt.Color(0, 0, 51));
        d9.setText("IMAGEN9");

        d10.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        d10.setForeground(new java.awt.Color(0, 0, 51));
        d10.setText("IMAGEN10");

        ENVIAR.setBackground(new java.awt.Color(153, 153, 255));
        ENVIAR.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        ENVIAR.setForeground(new java.awt.Color(0, 0, 51));
        ENVIAR.setText("ENVIAR");
        ENVIAR.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        ENVIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENVIARMouseClicked(evt);
            }
        });

        PUNTOSF.setBackground(new java.awt.Color(204, 204, 255));
        PUNTOSF.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        PUNTOSF.setForeground(new java.awt.Color(0, 0, 153));
        PUNTOSF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        PUNTOSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUNTOSFActionPerformed(evt);
            }
        });

        PUNTOS10.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS10.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS10.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS1.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS1.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS1.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));
        PUNTOS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUNTOS1ActionPerformed(evt);
            }
        });

        PUNTOS2.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS2.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS2.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS3.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS3.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS3.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS4.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS4.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS4.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS5.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS5.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS5.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS6.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS6.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS6.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS7.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS7.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS7.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS8.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS8.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS8.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        PUNTOS9.setBackground(new java.awt.Color(153, 153, 255));
        PUNTOS9.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS9.setForeground(new java.awt.Color(0, 0, 102));
        PUNTOS9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(d4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PUNTOS5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PUNTOS3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PUNTOS4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PUNTOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(d2)
                        .addGap(22, 22, 22)
                        .addComponent(PUNTOS2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(d10)
                        .addGap(18, 18, 18)
                        .addComponent(PUNTOS10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(d9)
                            .addGap(22, 22, 22)
                            .addComponent(PUNTOS9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(d8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PUNTOS8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(d7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PUNTOS7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(d6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PUNTOS6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LOGO)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(PUNTOSF, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(LOGO))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PUNTOS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PUNTOS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUNTOS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUNTOS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUNTOS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUNTOS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d9)
                    .addComponent(PUNTOS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUNTOS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d10)
                    .addComponent(PUNTOS10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUNTOS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PUNTOSF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TOTALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TOTALMouseClicked
        

        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALMouseClicked

    private void TOTAL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TOTAL1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTAL1MouseClicked

    private void ENVIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENVIARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ENVIARMouseClicked

    private void PUNTOSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUNTOSFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUNTOSFActionPerformed

    private void PUNTOS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUNTOS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUNTOS1ActionPerformed

    private void TOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALActionPerformed
// TODO add your handling code here:
        int Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9, Num10, Total;
        Num1=Integer.parseInt(PUNTOS1.getText());
        Num2=Integer.parseInt(PUNTOS2.getText());
        Num3=Integer.parseInt(PUNTOS3.getText());
        Num4=Integer.parseInt(PUNTOS4.getText());
        Num5=Integer.parseInt(PUNTOS5.getText());
        Num6=Integer.parseInt(PUNTOS6.getText());
        Num7=Integer.parseInt(PUNTOS7.getText());
        Num8=Integer.parseInt(PUNTOS8.getText());
        Num9=Integer.parseInt(PUNTOS9.getText());
        Num10=Integer.parseInt(PUNTOS10.getText());
        
        Total=Num1+Num2+Num3+Num4+Num5+Num6+Num7+Num8+Num9+Num10;
        PUNTOSF.setText(String.valueOf(Total));
    }//GEN-LAST:event_TOTALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATOS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENVIAR;
    private javax.swing.JLabel LOGO;
    private javax.swing.JTextField PUNTOS1;
    private javax.swing.JTextField PUNTOS10;
    private javax.swing.JTextField PUNTOS2;
    private javax.swing.JTextField PUNTOS3;
    private javax.swing.JTextField PUNTOS4;
    private javax.swing.JTextField PUNTOS5;
    private javax.swing.JTextField PUNTOS6;
    private javax.swing.JTextField PUNTOS7;
    private javax.swing.JTextField PUNTOS8;
    private javax.swing.JTextField PUNTOS9;
    private javax.swing.JTextField PUNTOSF;
    private javax.swing.JButton TOTAL;
    private javax.swing.JButton TOTAL1;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
