/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_experto_rorschach;

/**
 *
 * @author boyst
 */
public class IMAGEN1 extends javax.swing.JFrame {

    /**
     * Creates new form IMAGEN1
     */
    public IMAGEN1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public static String puntos = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IMAGEN1 = new javax.swing.JLabel();
        SIGUIENTE = new javax.swing.JButton();
        IMAGEN11 = new javax.swing.JLabel();
        MARIPOSA = new javax.swing.JButton();
        MURCIELAGO = new javax.swing.JButton();
        MASCARA = new javax.swing.JButton();
        ELEFANTE = new javax.swing.JButton();
        PUNTOS = new javax.swing.JTextField();
        ENVIAR = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_experto_rorschach/1.jpg"))); // NOI18N
        LOGO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        jLabel2.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("TEST DE PERSONALIDAD ");

        jLabel5.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("RORSCHACH");

        IMAGEN1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        IMAGEN1.setForeground(new java.awt.Color(0, 0, 51));
        IMAGEN1.setText("IMAGEN 1");

        SIGUIENTE.setBackground(new java.awt.Color(153, 153, 255));
        SIGUIENTE.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        SIGUIENTE.setForeground(new java.awt.Color(0, 0, 51));
        SIGUIENTE.setText("SIGUIENTE");
        SIGUIENTE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SIGUIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGUIENTEMouseClicked(evt);
            }
        });

        IMAGEN11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_experto_rorschach/FIGURA1.jpg"))); // NOI18N
        IMAGEN11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MARIPOSA.setBackground(new java.awt.Color(153, 153, 255));
        MARIPOSA.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        MARIPOSA.setForeground(new java.awt.Color(0, 0, 51));
        MARIPOSA.setText("MARIPOSA");
        MARIPOSA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MARIPOSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MARIPOSAActionPerformed(evt);
            }
        });

        MURCIELAGO.setBackground(new java.awt.Color(153, 153, 255));
        MURCIELAGO.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        MURCIELAGO.setForeground(new java.awt.Color(0, 0, 51));
        MURCIELAGO.setText("MURCIELAGO");
        MURCIELAGO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MURCIELAGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MURCIELAGOActionPerformed(evt);
            }
        });

        MASCARA.setBackground(new java.awt.Color(153, 153, 255));
        MASCARA.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        MASCARA.setForeground(new java.awt.Color(0, 0, 51));
        MASCARA.setText("MASCARA ");
        MASCARA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MASCARA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MASCARAActionPerformed(evt);
            }
        });

        ELEFANTE.setBackground(new java.awt.Color(153, 153, 255));
        ELEFANTE.setFont(new java.awt.Font("Century", 1, 11)); // NOI18N
        ELEFANTE.setForeground(new java.awt.Color(0, 0, 51));
        ELEFANTE.setText("ELEFANTE");
        ELEFANTE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ELEFANTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELEFANTEActionPerformed(evt);
            }
        });

        PUNTOS.setBackground(new java.awt.Color(204, 204, 255));
        PUNTOS.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        PUNTOS.setForeground(new java.awt.Color(0, 0, 153));
        PUNTOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        PUNTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUNTOSActionPerformed(evt);
            }
        });

        ENVIAR.setBackground(new java.awt.Color(0, 0, 153));
        ENVIAR.setFont(new java.awt.Font("Century", 1, 10)); // NOI18N
        ENVIAR.setForeground(new java.awt.Color(0, 0, 102));
        ENVIAR.setText("ENVIAR");
        ENVIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENVIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LOGO)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(IMAGEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MASCARA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(MARIPOSA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MURCIELAGO))
                                    .addComponent(ELEFANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(ENVIAR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(PUNTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IMAGEN11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))
                        .addGap(19, 26, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IMAGEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addComponent(LOGO))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(IMAGEN11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(MARIPOSA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MURCIELAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MASCARA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ELEFANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(PUNTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ENVIAR)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MURCIELAGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MURCIELAGOActionPerformed
this.PUNTOS.setText("12");        // TODO add your handling code here:
    }//GEN-LAST:event_MURCIELAGOActionPerformed

    private void MASCARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MASCARAActionPerformed
       this.PUNTOS.setText("13"); // TODO add your handling code here:
    }//GEN-LAST:event_MASCARAActionPerformed

    private void ELEFANTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELEFANTEActionPerformed
       this.PUNTOS.setText("14"); // TODO add your handling code here:
    }//GEN-LAST:event_ELEFANTEActionPerformed

    private void SIGUIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGUIENTEMouseClicked
IMAGEN2 imagen2=new IMAGEN2();
imagen2.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_SIGUIENTEMouseClicked

    private void MARIPOSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MARIPOSAActionPerformed
this.PUNTOS.setText("11");     // TODO add your handling code here:
    }//GEN-LAST:event_MARIPOSAActionPerformed

    private void ENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENVIARActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_ENVIARActionPerformed

    private void PUNTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUNTOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUNTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMAGEN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMAGEN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMAGEN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMAGEN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMAGEN1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ELEFANTE;
    private javax.swing.JButton ENVIAR;
    private javax.swing.JLabel IMAGEN1;
    private javax.swing.JLabel IMAGEN11;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton MARIPOSA;
    private javax.swing.JButton MASCARA;
    private javax.swing.JButton MURCIELAGO;
    private javax.swing.JTextField PUNTOS;
    private javax.swing.JButton SIGUIENTE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
